stages:
- name: package
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn clean package
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: docker build -f Dockerfile -t spring-k8s-test:v1 .
      tag: spring-k8s-test:v1
      pushRemote: true
      registry: index.docker.io
- name: run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
